### ISSUE TITLE
Seeking Information About Proxy Deposit Contracts

### ISSUE THREAD

**Issue by asdv23** [zkLinkProtocol/zklink-contracts#30]
Hello Everyone,

I've been exploring the project's documentation and came across mentions of 'proxy deposit contracts' and a 'proxy deposit contract factory.' However, I couldn't locate these contracts in the project's repository.

I'm eager to learn more about these contracts and how they work. Could someone please provide insights or direct me to the relevant resources for further information? Any help would be greatly appreciated.

Thank you for your time and assistance.

https://docs.zk.link/wallet-and-user-fund-streamline/deposit#deposit-functions
![image](https://github.com/zkLinkProtocol/zklink-contracts/assets/115535473/1336588a-eda5-4790-bccd-160116e2177b)

**Comment by zkbenny** [comment]
This is a future under development。Here are some details:
* User use his wallet (e.g. metamask) to sign a message as the seed to generate a l2 private key
* Calculate `proxy deposit contract` address of `CREATE2` offchain  as the deposit receive address
```solidity
// creatorAddress: the proxy deposit factory address
// salt: calculate from l2 pubkey hash
// codeHash: the init code hash of proxy deposit contract
  address depositAddress = address(
      uint160(uint256(keccak256(abi.encodePacked(bytes1(0xff), creatorAddress, salt, codeHash))))
  );
```
* When the `proxy deposit address` receiving some tokens then a relayer can notify `proxy deposit factory contract` to generate the `proxy deposit contract` without permission
* A relayer can call `proxy deposit function` to zklink from this `proxy deposit address`  without permission and take some fee.
